name: "test-on-pr"

on: [push, pull_request]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
            target: "aarch64-apple-darwin"
            artifact: "macos-silicon"
          - platform: "macos-15-intel" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
            target: "x86_64-apple-darwin"
            artifact: "macos-intel"
          - platform: "ubuntu-24.04" # Tauri v2 needs webkitgtk 4.1+.
            args: ""
            target: ""
            artifact: "ubuntu"
          - platform: "windows-latest"
            args: ""
            target: ""
            artifact: "windows"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-24.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.target }}

      - name: install dependencies
        run: npm install

      - name: build tauri app
        uses: tauri-apps/tauri-action@v0
        with:
          args: ${{ matrix.args }}

      - name: upload bundles
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundle-${{ matrix.artifact }}
          path: |
            src-tauri/target/**/release/bundle/**
            src-tauri/target/**/debug/bundle/**
            target/**/release/bundle/**
            target/**/debug/bundle/**
